### ISSUE TITLE
Doesn't seem to work in Foundry v9.x

### ISSUE THREAD

**Issue by geoidesic** [vtt-lair/foundry-group-initiative#34]
Here's the error:
```
Uncaught (in promise) A: Error detected in module Group Initiative. It is likely this module has not been updated for FVTT Version 9.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/vtt-lair/foundry-group-initiative

Ask the community for support:
- FoundryVTT Discord's #modules-troubleshooting channel: https://discord.gg/foundryvtt
- FoundryVTT Reddit: https://www.reddit.com/r/FoundryVTT

== Technical Details:
Detected by libWrapper.
Package ID= group-initiative
Error= Cannot unregister 'Combat.prototype.rollAll' by module group-initiative as no such wrapper has been registered

[Detected 1 package: group-initiative]
    at ue (https://foundryvtt.3dmentia.com/modules/lib-wrapper/lib-wrapper.js:1:43946)
    at Function.🎁unregister [as unregister] (https://foundryvtt.3dmentia.com/modules/lib-wrapper/lib-wrapper.js:1:48070)
    at https://foundryvtt.3dmentia.com/modules/group-initiative/group-initiative.js:427:16
    at Function._call (https://foundryvtt.3dmentia.com/scripts/foundry.js:294:14)
    at Function.callAll (https://foundryvtt.3dmentia.com/scripts/foundry.js:253:12)
    at ClientDatabaseBackend.callback (https://foundryvtt.3dmentia.com/scripts/foundry.js:10439:13)
    at https://foundryvtt.3dmentia.com/scripts/foundry.js:10379:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleDeleteDocuments (https://foundryvtt.3dmentia.com/scripts/foundry.js:10379:33)
    at ClientDatabaseBackend._deleteDocuments (https://foundryvtt.3dmentia.com/scripts/foundry.js:10286:17)
    at async Function.deleteDocuments (https://foundryvtt.3dmentia.com/common/abstract/document.mjs:410:21)
    at async Combat.delete (https://foundryvtt.3dmentia.com/common/abstract/document.mjs:471:21)
    at async CombatTracker._onCombatControl (https://foundryvtt.3dmentia.com/scripts/foundry.js:58363:15)
```

**Comment by vtt-lair** [comment]
That's weird, I'm running it on 9 (9.242) myself with no issues on Roll NPC or Roll All. For interest sake, what happens when you run it with just Group Initiative and libWrapper?

**Comment by vtt-lair** [comment]
It could be that you have another module that is also overriding the roll buttons and that could be causing my override not to be created.

The following module might also override:
- Mob Attack Tool - (I believe they have an implementation of group initiative that was done when this module was not being maintained before I took it over. This can be flagged in it's settings though)

**Comment by geoidesic** [comment]
No. I tried Mob Attack Tool on it's own – i.e. all other modules disabled – and got the same thing. The initiative dice does roll but the value doesn't show up in the combat tracker.

**Comment by geoidesic** [comment]
Ok, yes. You're right it is Mob Attack Tool. 
The settings you speak of for Mob Attack Tool don't help. Mob Attack Tool is completely broken and is indeed what is breaking the initiative rolls – I tried it on it's own with no other modules and it still breaks the initiative roll.

For you module, what doesn't work is group by name, which is a pity but not a deal breaker.

**Comment by vtt-lair** [comment]
Yeah, I've created a setting for group name and flagged it as experimental. It was acting up too much and giving a lot of issues. So I disabled it by default while I try and refactor the code.
