### ISSUE TITLE
No longer works once on V12

### ISSUE THREAD

**Issue by SilverwolfNL** [vtt-lair/foundry-group-initiative#54]
Not sure if this module is still being maintained. but v12 is gving this:

Error: You are accessing the Combatant5e "data" field of which was deprecated in v10 and replaced with "system". Continued usage of pre-v10 ".data" paths is no longer supported"
    at get data (foundry-esm.js:11866:15)
    at group-initiative.js:94:90
    at Array.reduce (<anonymous>)
    at Combat5e.rollGroupInitiative (group-initiative.js:91:32)
    at Combat5e.rollAll (group-initiative.js:71:51)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Combat.prototype.rollAll#0 (libWrapper-wrapper.js:189:20)
    at CombatTracker5e._onCombatControl (foundry.js:89790:38)
    at HTMLAnchorElement.<anonymous> (foundry.js:89727:51)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)

**Comment by vtt-lair** [comment]
Thanks, I'll have a look at this soon. Obviously something I missed when converting to v11

**Comment by vtt-lair** [comment]
I believe this should be fixed in version 2.1.6, will you let me know whether it's working for you in v12, @SilverwolfNL?

**Comment by SilverwolfNL** [comment]
Seems to be working fine now , thank you
